// Generated by tools/gen_spec.py -- do not edit.
//
// Every flag, default and tooltip below is read straight out of
// ut3conv.py's, batch.py's and repoint_package.py's argparse
// definitions. Re-run the
// generator after changing a flag in either script.
#pragma once

#include "spec.h"

namespace spec {

inline const Opt kT3dOptions[] = {
    { "package", "", "package", Kind::Text, "", "the UT3 package to read, normally a .ut3 under UTGame/CookedPC/Maps", true, false, Browse::OpenPackage, {  } },
    { "output", "--output", "output", Kind::Text, "", "output .t3d path", true, false, Browse::SavePath, {  } },
    { "texture_package", "--texture-package", "texture-package", Kind::Text, "", "package name to qualify texture references with", false, false, Browse::None, {  } },
    { "textures", "--textures", "textures", Kind::Text, "<install-root>", "where to write the generated package (textures, meshes, terrain, sounds). Defaults to the UT2004 install root, which is the only place ucc make can build it from", false, false, Browse::Folder, {  } },
    { "max_texture_size", "--max-texture-size", "max-texture-size", Kind::Int, "4096", "largest mip to export (default 4096)", false, false, Browse::None, {  } },
    { "scale", "--scale", "scale", Kind::Float, "1.0", "world scale factor (default 1.0)", false, false, Browse::None, {  } },
    { "surface_scale", "--surface-scale", "surface-scale", Kind::Float, "1.0", "extra multiplier on BSP surface UVs; 1.0 reproduces UT3's own tiling (the real conversion is UE3_BSP_UV_SCALE)", false, false, Browse::None, {  } },
    { "no_package", "--no-package", "no-package", Kind::Flag, "false", "emit only the .t3d, with no buildable asset package", false, false, Browse::None, {  } },
    { "no_materials", "--no-materials", "no-materials", Kind::Flag, "false", "do not build UE2 Shader/FinalBlend objects for translucent, additive or unlit surfaces; every surface falls back to a flat texture, which is what the converter did before", false, false, Browse::None, {  } },
    { "all_textures", "--all-textures", "all-textures", Kind::Flag, "false", "import every texture each material refers to, not just the one drawn -- normals, speculars, masks and the branches a static switch turns off. Nothing references them; they are there for hand-editing the package afterwards, and they cost package size", false, false, Browse::None, {  } },
    { "no_meshes", "--no-meshes", "no-meshes", Kind::Flag, "false", "omit static meshes (requires --textures otherwise)", false, false, Browse::None, {  } },
    { "no_terrain", "--no-terrain", "no-terrain", Kind::Flag, "false", "omit converted terrain", false, false, Browse::None, {  } },
    { "no_movers", "--no-movers", "no-movers", Kind::Flag, "false", "omit Movers (Matinee-animated InterpActors then stay parked where UT3 placed them)", false, false, Browse::None, {  } },
    { "no_sounds", "--no-sounds", "no-sounds", Kind::Flag, "false", "omit ambient sounds (they need ffmpeg to decode UT3's Ogg)", false, false, Browse::None, {  } },
    { "no_lights", "--no-lights", "no-lights", Kind::Flag, "false", "omit converted lights", false, false, Browse::None, {  } },
    { "no_pickups", "--no-pickups", "no-pickups", Kind::Flag, "false", "omit weapon bases, health, armour and powerups", false, false, Browse::None, {  } },
    { "no_paths", "--no-paths", "no-paths", Kind::Flag, "false", "omit PathNodes and jump pads (bots then have no paths)", false, false, Browse::None, {  } },
    { "no_player_starts", "--no-player-starts", "no-player-starts", Kind::Flag, "false", "omit PlayerStarts", false, false, Browse::None, {  } },
    { "no_objectives", "--no-objectives", "no-objectives", Kind::Flag, "false", "omit team game objectives (CTF flag bases)", false, false, Browse::None, {  } },
    { "no_teleporters", "--no-teleporters", "no-teleporters", Kind::Flag, "false", "omit teleporters", false, false, Browse::None, {  } },
    { "no_teleporter_effect", "--no-teleporter-effect", "no-teleporter-effect", Kind::Flag, "false", "emit the Teleporter alone, without the portal meshes UT2004's own DM-Deck17 dresses its teleporters with (a converted teleporter is otherwise invisible)", false, false, Browse::None, {  } },
    { "no_onslaught", "--no-onslaught", "no-onslaught", Kind::Flag, "false", "omit Warfare/Onslaught conversion (power cores, nodes, the link setup and vehicle factories)", false, false, Browse::None, {  } },
    { "no_volumes", "--no-volumes", "no-volumes", Kind::Flag, "false", "omit BlockingVolumes (UT3's invisible walls; they keep players inside the intended play area)", false, false, Browse::None, {  } },
    { "no_skybox", "--no-skybox", "no-skybox", Kind::Flag, "false", "omit the SkyZoneInfo room (the world brush then shows a flat texture)", false, false, Browse::None, {  } },
    { "no_minimap", "--no-minimap", "no-minimap", Kind::Flag, "false", "do not draw a radar background from the terrain", false, false, Browse::None, {  } },
    { "no_zone_info", "--no-zone-info", "no-zone-info", Kind::Flag, "false", "do not emit the ZoneInfo that terrain needs to render", false, false, Browse::None, {  } },
    { "keep_effect_meshes", "--keep-effect-meshes", "keep-effect-meshes", Kind::Flag, "false", "convert unlit translucent effect meshes (light beams, fog sheets) instead of skipping them; they import as opaque surfaces", false, false, Browse::None, {  } },
    { "light_gain", "--light-gain", "light-gain", Kind::Float, "32.0", "UE3 brightness 1.0 maps to this UE2 LightBrightness (default 32)", false, false, Browse::None, {  } },
    { "ambient", "--ambient", "ambient", Kind::Int, "", "set the zone's AmbientBrightness (0-255) outright, overriding whatever the SkyLights give. A UDK map bakes its fill light into lightmaps and often has no SkyLight, leaving nothing for --ambient-gain to scale", false, false, Browse::None, {  } },
    { "ambient_gain", "--ambient-gain", "ambient-gain", Kind::Float, "16.0", "scales the UT3 SkyLight into a UT2004 AmbientBrightness (default 16)", false, false, Browse::None, {  } },
    { "light_radius_scale", "--light-radius-scale", "light-radius-scale", Kind::Float, "1.0", "widen every light's radius by this factor (default 1.0)", false, false, Browse::None, {  } },
    { "sky_mode", "--sky-mode", "sky-mode", Kind::Choice, "skybox", "skybox puts the dome in a SkyZoneInfo room so it reads as infinitely distant, at UT3's proportions; inline keeps it as ordinary level geometry, capped by UE2's 65536uu far plane", false, false, Browse::None, { "skybox", "inline" } },
    { "sky_dome_margin", "--sky-dome-margin", "sky-dome-margin", Kind::Float, "1.25", "how far past the furthest geometry the inline dome sits", false, false, Browse::None, {  } },
    { "sky_merge_distance", "--sky-merge-distance", "sky-merge-distance", Kind::Float, "1.0", "merge backdrop meshes landing this close in the sky room (invisible at skybox scale; avoids co-located warnings)", false, false, Browse::None, {  } },
    { "shrink_backdrop", "--shrink-backdrop", "shrink-backdrop", Kind::Flag, "false", "always shrink UT3's distant backdrop meshes into the sky room by the dome's scale factor, instead of leaving them in the level at their true positions. Happens automatically anyway when reaching them would cross UE2's 262144uu world limit", false, false, Browse::None, {  } },
    { "keep_backdrop", "--keep-backdrop", "keep-backdrop", Kind::Flag, "false", "leave the backdrop in the level even when the void needed to enclose it runs past UE2's world limit (the map will be clamped and broken; for diagnosing that)", false, false, Browse::None, {  } },
    { "world_margin", "--world-margin", "world-margin", Kind::Float, "1024.0", "padding around the geometry for the world brush (default 1024)", false, false, Browse::None, {  } },
    { "world_cell", "--world-cell", "world-cell", Kind::Float, "0.0", "tile the enclosing void into cells this big (0 = one box, the default; tiled cells have been seen to carve only partly)", false, false, Browse::None, {  } },
    { "no_world_brush", "--no-world-brush", "no-world-brush", Kind::Flag, "false", "omit the enclosing subtractive brush (UT2004 is subtractive, UT3 additive)", false, false, Browse::None, {  } },
    { "deco_density", "--deco-density", "deco-density", Kind::Float, "0.5", "how thickly UT3's terrain foliage is scattered as UT2004 decoration layers; 0 omits them (default 0.5). UT3 states where the ground cover goes but not how much", false, false, Browse::None, {  } },
    { "terrain_layer_scale", "--terrain-layer-scale", "terrain-layer-scale", Kind::Float, "0.0", "force one texture tiling on every terrain layer; by default each layer derives its own from UT3's MappingScale, per axis", false, false, Browse::None, {  } },
    { "mover_keys", "--mover-keys", "mover-keys", Kind::Int, "24", "keyframes to resample a Matinee move track into (default 24, the size of Mover.KeyPos)", false, false, Browse::None, {  } },
    { "sound_gain", "--sound-gain", "sound-gain", Kind::Float, "1.0", "scales every ambient's volume; UE3 1.0 maps to SoundVolume 255 at the default 1.0", false, false, Browse::None, {  } },
    { "onslaught_specials", "--onslaught-specials", "onslaught-specials", Kind::Flag, "false", "place the OnslaughtSpecials2 core/node classes instead of stock Onslaught, keeping countdown nodes and standalone flags. Requires that mod: without it the editor drops the actors silently and the map has no power cores", false, false, Browse::None, {  } },
    { "countdown_time", "--countdown-time", "countdown-time", Kind::Int, "120", "seconds a UT3 countdown node must be held (default 120); UT3 does not state one in the map", false, false, Browse::None, {  } },
    { "countdown_damage", "--countdown-damage", "countdown-damage", Kind::Int, "901", "damage a completed countdown deals to the enemy core (default 901, ONS-Tyrant's value, against a core with 4500 health); needs --onslaught-specials", false, false, Browse::None, {  } },
    { "node_rise", "--node-rise", "node-rise", Kind::Float, "0.0", "extra height for a power node that rests on a brush, on top of standing its mesh and touch cylinder clear of the floor; raise it if a node still has to be jumped on", false, false, Browse::None, {  } },
    { "vehicle_rise", "--vehicle-rise", "vehicle-rise", Kind::Float, "32.0", "how far above its stated spot a vehicle factory is placed, so a spawning vehicle does not drop through the mesh it rests on (default 32); 0 keeps UT3's exact position", false, false, Browse::None, {  } },
    { "minimap_size", "--minimap-size", "minimap-size", Kind::Int, "256", "radar background resolution, square (default 256)", false, false, Browse::None, {  } },
    { "no_sublevels", "--no-sublevels", "no-sublevels", Kind::Flag, "false", "do not merge the streaming sub-levels the persistent level always loads; an Angels Fall First map is nearly empty without them, since its content is streamed in", false, false, Browse::None, {  } },
};

inline const Section kT3dSections[] = {
    { "Required", 0, 2 },
    { "Package and scale", 2, 10 },
    { "Leave out", 10, 27 },
    { "Lighting", 27, 31 },
    { "Sky", 31, 36 },
    { "World brush", 36, 39 },
    { "Terrain", 39, 41 },
    { "Movers and sound", 41, 43 },
    { "Warfare / Onslaught", 43, 48 },
    { "Minimap", 48, 49 },
    { "Other", 49, 50 },
};

inline const Opt kInfoOptions[] = {
    { "package", "", "package", Kind::Text, "", "the UT3 package to read, normally a .ut3 under UTGame/CookedPC/Maps", true, false, Browse::OpenPackage, {  } },
};

inline const Opt kClassesOptions[] = {
    { "package", "", "package", Kind::Text, "", "the UT3 package to read, normally a .ut3 under UTGame/CookedPC/Maps", true, false, Browse::OpenPackage, {  } },
    { "number", "--number", "number", Kind::Int, "40", "", false, false, Browse::None, {  } },
};

inline const Opt kListOptions[] = {
    { "package", "", "package", Kind::Text, "", "the UT3 package to read, normally a .ut3 under UTGame/CookedPC/Maps", true, false, Browse::OpenPackage, {  } },
    { "cls", "--cls", "cls", Kind::Text, "", "filter by class name", false, false, Browse::None, {  } },
    { "match", "--match", "match", Kind::Text, "", "glob match on object name", false, false, Browse::None, {  } },
    { "number", "--number", "number", Kind::Int, "50", "", false, false, Browse::None, {  } },
};

inline const Opt kPropsOptions[] = {
    { "package", "", "package", Kind::Text, "", "the UT3 package to read, normally a .ut3 under UTGame/CookedPC/Maps", true, false, Browse::OpenPackage, {  } },
    { "object", "", "object", Kind::Text, "", "export index, name, or dotted path", true, false, Browse::None, {  } },
    { "number", "--number", "number", Kind::Int, "3", "max matching objects to dump", false, false, Browse::None, {  } },
    { "components", "--components", "components", Kind::Flag, "false", "", false, false, Browse::None, {  } },
};

inline const Opt kImportsOptions[] = {
    { "package", "", "package", Kind::Text, "", "the UT3 package to read, normally a .ut3 under UTGame/CookedPC/Maps", true, false, Browse::OpenPackage, {  } },
    { "match", "--match", "match", Kind::Text, "", "", false, false, Browse::None, {  } },
    { "number", "--number", "number", Kind::Int, "50", "", false, false, Browse::None, {  } },
};

inline const Opt kBatchOptions[] = {
    { "list", "--list", "list", Kind::Flag, "false", "show what would run and stop", false, false, Browse::None, {  } },
    { "match", "--match", "match", Kind::Text, "", "only maps whose name contains this", false, false, Browse::None, {  } },
    { "variants", "--variants", "variants", Kind::Flag, "false", "also convert UT3's campaign variants (_SP, _Necris, _Leviathan), which are near-duplicates of the versal maps and cost a package each", false, false, Browse::None, {  } },
    { "build", "--build", "build", Kind::Flag, "false", "also run ucc make for each map, one package at a time", false, false, Browse::None, {  } },
    { "dry_run", "--dry-run", "dry-run", Kind::Flag, "false", "print each step without doing any of it", false, false, Browse::None, {  } },
    { "skip_converted", "--skip-converted", "skip-converted", Kind::Flag, "false", "skip maps whose t3d is already in the editor folder", false, false, Browse::None, {  } },
    { "flag", "--flag", "flag", Kind::Text, "[]", "extra ut3conv flags for every map, split on spaces and appended after the per-map ones, so they win. Repeatable. Example: --flag '--max-texture-size 2048'", false, false, Browse::None, {  } },
};

inline const Opt kRepointOptions[] = {
    { "old", "", "old", Kind::Text, "", "the package name in use now", false, false, Browse::None, {  } },
    { "new", "", "new", Kind::Text, "", "what to call it, exactly as long as the old one", false, false, Browse::None, {  } },
    { "files", "", "files", Kind::Text, "", "every file that names it -- both the .ut2 and its .utx, since the map imports a class of that name as well as the package", false, true, Browse::None, {  } },
    { "list", "--list", "list", Kind::Text, "", "show the packages FILE imports, and stop", false, false, Browse::OpenPackage, {  } },
};

inline const Command kInspectCommands[] = {
    { "info", kInfoOptions, 1 },
    { "classes", kClassesOptions, 2 },
    { "list", kListOptions, 4 },
    { "props", kPropsOptions, 4 },
    { "imports", kImportsOptions, 3 },
};

inline constexpr int kT3dOptionCount = 50;
inline constexpr int kT3dSectionCount = 11;
inline constexpr int kBatchOptionCount = 7;
inline constexpr int kRepointOptionCount = 4;
inline constexpr int kInspectCommandCount = 5;

}  // namespace spec
